/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobJobIdEditRouteImport } from './routes/job.$jobId.edit'

const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdEditRoute = JobJobIdEditRouteImport.update({
  id: '/job/$jobId/edit',
  path: '/job/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/talent': typeof TalentRoute
  '/job/$jobId/edit': typeof JobJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/talent': typeof TalentRoute
  '/job/$jobId/edit': typeof JobJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/talent': typeof TalentRoute
  '/job/$jobId/edit': typeof JobJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/messages'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/job/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/messages'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/job/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/messages'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/job/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  MessagesRoute: typeof MessagesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TalentRoute: typeof TalentRoute
  JobJobIdEditRoute: typeof JobJobIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/edit': {
      id: '/job/$jobId/edit'
      path: '/job/$jobId/edit'
      fullPath: '/job/$jobId/edit'
      preLoaderRoute: typeof JobJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  MessagesRoute: MessagesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TalentRoute: TalentRoute,
  JobJobIdEditRoute: JobJobIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
