/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as JoinRouteImport } from './routes/join'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreelancerIndexRouteImport } from './routes/freelancer.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as FreelancerSettingsRouteImport } from './routes/freelancer.settings'
import { Route as FreelancerProposalsRouteImport } from './routes/freelancer.proposals'
import { Route as FreelancerEarningsRouteImport } from './routes/freelancer.earnings'
import { Route as FreelancerFindWorkIndexRouteImport } from './routes/freelancer.find-work.index'
import { Route as JobJobIdShortlistRouteImport } from './routes/job.$jobId.shortlist'
import { Route as JobJobIdEditRouteImport } from './routes/job.$jobId.edit'
import { Route as JobJobIdApplicantsRouteImport } from './routes/job.$jobId.applicants'
import { Route as FreelancerFindWorkJobIdIndexRouteImport } from './routes/freelancer.find-work.$jobId.index'
import { Route as FreelancerFindWorkJobIdApplyRouteImport } from './routes/freelancer.find-work.$jobId.apply'
import { Route as JobJobIdApplicantsApplicantIdMessageRouteImport } from './routes/job.$jobId.applicants.$applicantId.message'

const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerIndexRoute = FreelancerIndexRouteImport.update({
  id: '/freelancer/',
  path: '/freelancer/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerSettingsRoute = FreelancerSettingsRouteImport.update({
  id: '/freelancer/settings',
  path: '/freelancer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerProposalsRoute = FreelancerProposalsRouteImport.update({
  id: '/freelancer/proposals',
  path: '/freelancer/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerEarningsRoute = FreelancerEarningsRouteImport.update({
  id: '/freelancer/earnings',
  path: '/freelancer/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerFindWorkIndexRoute = FreelancerFindWorkIndexRouteImport.update({
  id: '/freelancer/find-work/',
  path: '/freelancer/find-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdShortlistRoute = JobJobIdShortlistRouteImport.update({
  id: '/job/$jobId/shortlist',
  path: '/job/$jobId/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdEditRoute = JobJobIdEditRouteImport.update({
  id: '/job/$jobId/edit',
  path: '/job/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdApplicantsRoute = JobJobIdApplicantsRouteImport.update({
  id: '/job/$jobId/applicants',
  path: '/job/$jobId/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerFindWorkJobIdIndexRoute =
  FreelancerFindWorkJobIdIndexRouteImport.update({
    id: '/freelancer/find-work/$jobId/',
    path: '/freelancer/find-work/$jobId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FreelancerFindWorkJobIdApplyRoute =
  FreelancerFindWorkJobIdApplyRouteImport.update({
    id: '/freelancer/find-work/$jobId/apply',
    path: '/freelancer/find-work/$jobId/apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobJobIdApplicantsApplicantIdMessageRoute =
  JobJobIdApplicantsApplicantIdMessageRouteImport.update({
    id: '/$applicantId/message',
    path: '/$applicantId/message',
    getParentRoute: () => JobJobIdApplicantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/join': typeof JoinRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/talent': typeof TalentRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/proposals': typeof FreelancerProposalsRoute
  '/freelancer/settings': typeof FreelancerSettingsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/job/$jobId/applicants': typeof JobJobIdApplicantsRouteWithChildren
  '/job/$jobId/edit': typeof JobJobIdEditRoute
  '/job/$jobId/shortlist': typeof JobJobIdShortlistRoute
  '/freelancer/find-work/': typeof FreelancerFindWorkIndexRoute
  '/freelancer/find-work/$jobId/apply': typeof FreelancerFindWorkJobIdApplyRoute
  '/freelancer/find-work/$jobId/': typeof FreelancerFindWorkJobIdIndexRoute
  '/job/$jobId/applicants/$applicantId/message': typeof JobJobIdApplicantsApplicantIdMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/join': typeof JoinRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/talent': typeof TalentRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/proposals': typeof FreelancerProposalsRoute
  '/freelancer/settings': typeof FreelancerSettingsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/freelancer': typeof FreelancerIndexRoute
  '/job/$jobId/applicants': typeof JobJobIdApplicantsRouteWithChildren
  '/job/$jobId/edit': typeof JobJobIdEditRoute
  '/job/$jobId/shortlist': typeof JobJobIdShortlistRoute
  '/freelancer/find-work': typeof FreelancerFindWorkIndexRoute
  '/freelancer/find-work/$jobId/apply': typeof FreelancerFindWorkJobIdApplyRoute
  '/freelancer/find-work/$jobId': typeof FreelancerFindWorkJobIdIndexRoute
  '/job/$jobId/applicants/$applicantId/message': typeof JobJobIdApplicantsApplicantIdMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/join': typeof JoinRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/talent': typeof TalentRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/proposals': typeof FreelancerProposalsRoute
  '/freelancer/settings': typeof FreelancerSettingsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/job/$jobId/applicants': typeof JobJobIdApplicantsRouteWithChildren
  '/job/$jobId/edit': typeof JobJobIdEditRoute
  '/job/$jobId/shortlist': typeof JobJobIdShortlistRoute
  '/freelancer/find-work/': typeof FreelancerFindWorkIndexRoute
  '/freelancer/find-work/$jobId/apply': typeof FreelancerFindWorkJobIdApplyRoute
  '/freelancer/find-work/$jobId/': typeof FreelancerFindWorkJobIdIndexRoute
  '/job/$jobId/applicants/$applicantId/message': typeof JobJobIdApplicantsApplicantIdMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/join'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/freelancer/earnings'
    | '/freelancer/proposals'
    | '/freelancer/settings'
    | '/settings/profile'
    | '/freelancer/'
    | '/job/$jobId/applicants'
    | '/job/$jobId/edit'
    | '/job/$jobId/shortlist'
    | '/freelancer/find-work/'
    | '/freelancer/find-work/$jobId/apply'
    | '/freelancer/find-work/$jobId/'
    | '/job/$jobId/applicants/$applicantId/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/join'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/freelancer/earnings'
    | '/freelancer/proposals'
    | '/freelancer/settings'
    | '/settings/profile'
    | '/freelancer'
    | '/job/$jobId/applicants'
    | '/job/$jobId/edit'
    | '/job/$jobId/shortlist'
    | '/freelancer/find-work'
    | '/freelancer/find-work/$jobId/apply'
    | '/freelancer/find-work/$jobId'
    | '/job/$jobId/applicants/$applicantId/message'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/join'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/freelancer/earnings'
    | '/freelancer/proposals'
    | '/freelancer/settings'
    | '/settings/profile'
    | '/freelancer/'
    | '/job/$jobId/applicants'
    | '/job/$jobId/edit'
    | '/job/$jobId/shortlist'
    | '/freelancer/find-work/'
    | '/freelancer/find-work/$jobId/apply'
    | '/freelancer/find-work/$jobId/'
    | '/job/$jobId/applicants/$applicantId/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  JoinRoute: typeof JoinRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PostJobRoute: typeof PostJobRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TalentRoute: typeof TalentRoute
  FreelancerEarningsRoute: typeof FreelancerEarningsRoute
  FreelancerProposalsRoute: typeof FreelancerProposalsRoute
  FreelancerSettingsRoute: typeof FreelancerSettingsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  FreelancerIndexRoute: typeof FreelancerIndexRoute
  JobJobIdApplicantsRoute: typeof JobJobIdApplicantsRouteWithChildren
  JobJobIdEditRoute: typeof JobJobIdEditRoute
  JobJobIdShortlistRoute: typeof JobJobIdShortlistRoute
  FreelancerFindWorkIndexRoute: typeof FreelancerFindWorkIndexRoute
  FreelancerFindWorkJobIdApplyRoute: typeof FreelancerFindWorkJobIdApplyRoute
  FreelancerFindWorkJobIdIndexRoute: typeof FreelancerFindWorkJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/': {
      id: '/freelancer/'
      path: '/freelancer'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof FreelancerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/settings': {
      id: '/freelancer/settings'
      path: '/freelancer/settings'
      fullPath: '/freelancer/settings'
      preLoaderRoute: typeof FreelancerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/proposals': {
      id: '/freelancer/proposals'
      path: '/freelancer/proposals'
      fullPath: '/freelancer/proposals'
      preLoaderRoute: typeof FreelancerProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/earnings': {
      id: '/freelancer/earnings'
      path: '/freelancer/earnings'
      fullPath: '/freelancer/earnings'
      preLoaderRoute: typeof FreelancerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/find-work/': {
      id: '/freelancer/find-work/'
      path: '/freelancer/find-work'
      fullPath: '/freelancer/find-work/'
      preLoaderRoute: typeof FreelancerFindWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/shortlist': {
      id: '/job/$jobId/shortlist'
      path: '/job/$jobId/shortlist'
      fullPath: '/job/$jobId/shortlist'
      preLoaderRoute: typeof JobJobIdShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/edit': {
      id: '/job/$jobId/edit'
      path: '/job/$jobId/edit'
      fullPath: '/job/$jobId/edit'
      preLoaderRoute: typeof JobJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/applicants': {
      id: '/job/$jobId/applicants'
      path: '/job/$jobId/applicants'
      fullPath: '/job/$jobId/applicants'
      preLoaderRoute: typeof JobJobIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/find-work/$jobId/': {
      id: '/freelancer/find-work/$jobId/'
      path: '/freelancer/find-work/$jobId'
      fullPath: '/freelancer/find-work/$jobId/'
      preLoaderRoute: typeof FreelancerFindWorkJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/find-work/$jobId/apply': {
      id: '/freelancer/find-work/$jobId/apply'
      path: '/freelancer/find-work/$jobId/apply'
      fullPath: '/freelancer/find-work/$jobId/apply'
      preLoaderRoute: typeof FreelancerFindWorkJobIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/applicants/$applicantId/message': {
      id: '/job/$jobId/applicants/$applicantId/message'
      path: '/$applicantId/message'
      fullPath: '/job/$jobId/applicants/$applicantId/message'
      preLoaderRoute: typeof JobJobIdApplicantsApplicantIdMessageRouteImport
      parentRoute: typeof JobJobIdApplicantsRoute
    }
  }
}

interface JobJobIdApplicantsRouteChildren {
  JobJobIdApplicantsApplicantIdMessageRoute: typeof JobJobIdApplicantsApplicantIdMessageRoute
}

const JobJobIdApplicantsRouteChildren: JobJobIdApplicantsRouteChildren = {
  JobJobIdApplicantsApplicantIdMessageRoute:
    JobJobIdApplicantsApplicantIdMessageRoute,
}

const JobJobIdApplicantsRouteWithChildren =
  JobJobIdApplicantsRoute._addFileChildren(JobJobIdApplicantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  JoinRoute: JoinRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PostJobRoute: PostJobRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TalentRoute: TalentRoute,
  FreelancerEarningsRoute: FreelancerEarningsRoute,
  FreelancerProposalsRoute: FreelancerProposalsRoute,
  FreelancerSettingsRoute: FreelancerSettingsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  FreelancerIndexRoute: FreelancerIndexRoute,
  JobJobIdApplicantsRoute: JobJobIdApplicantsRouteWithChildren,
  JobJobIdEditRoute: JobJobIdEditRoute,
  JobJobIdShortlistRoute: JobJobIdShortlistRoute,
  FreelancerFindWorkIndexRoute: FreelancerFindWorkIndexRoute,
  FreelancerFindWorkJobIdApplyRoute: FreelancerFindWorkJobIdApplyRoute,
  FreelancerFindWorkJobIdIndexRoute: FreelancerFindWorkJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
