/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as FreelancerIndexRouteImport } from './routes/freelancer.index'
import { Route as AgencyIndexRouteImport } from './routes/agency.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as OnboardingBusinessRouteImport } from './routes/onboarding.business'
import { Route as FreelancerSettingsRouteImport } from './routes/freelancer.settings'
import { Route as FreelancerProposalsRouteImport } from './routes/freelancer.proposals'
import { Route as FreelancerProfileRouteImport } from './routes/freelancer.profile'
import { Route as FreelancerEarningsRouteImport } from './routes/freelancer.earnings'
import { Route as AgencyProfileRouteImport } from './routes/agency.profile'
import { Route as StatsSpendingIndexRouteImport } from './routes/stats.spending.index'
import { Route as FreelancerFindWorkIndexRouteImport } from './routes/freelancer.find-work.index'
import { Route as JobJobIdShortlistRouteImport } from './routes/job.$jobId.shortlist'
import { Route as JobJobIdEditRouteImport } from './routes/job.$jobId.edit'
import { Route as JobJobIdApplicantsRouteImport } from './routes/job.$jobId.applicants'
import { Route as FreelancerFindWorkJobIdIndexRouteImport } from './routes/freelancer.find-work.$jobId.index'
import { Route as StatsSpendingPaymentPaymentIdRouteImport } from './routes/stats.spending.payment.$paymentId'
import { Route as StatsSpendingContractContractIdRouteImport } from './routes/stats.spending.contract.$contractId'
import { Route as FreelancerFindWorkJobIdApplyRouteImport } from './routes/freelancer.find-work.$jobId.apply'
import { Route as JobJobIdApplicantsApplicantIdMessageRouteImport } from './routes/job.$jobId.applicants.$applicantId.message'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatsRoute,
} as any)
const FreelancerIndexRoute = FreelancerIndexRouteImport.update({
  id: '/freelancer/',
  path: '/freelancer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyIndexRoute = AgencyIndexRouteImport.update({
  id: '/agency/',
  path: '/agency/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBusinessRoute = OnboardingBusinessRouteImport.update({
  id: '/onboarding/business',
  path: '/onboarding/business',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerSettingsRoute = FreelancerSettingsRouteImport.update({
  id: '/freelancer/settings',
  path: '/freelancer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerProposalsRoute = FreelancerProposalsRouteImport.update({
  id: '/freelancer/proposals',
  path: '/freelancer/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerProfileRoute = FreelancerProfileRouteImport.update({
  id: '/freelancer/profile',
  path: '/freelancer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerEarningsRoute = FreelancerEarningsRouteImport.update({
  id: '/freelancer/earnings',
  path: '/freelancer/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyProfileRoute = AgencyProfileRouteImport.update({
  id: '/agency/profile',
  path: '/agency/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSpendingIndexRoute = StatsSpendingIndexRouteImport.update({
  id: '/spending/',
  path: '/spending/',
  getParentRoute: () => StatsRoute,
} as any)
const FreelancerFindWorkIndexRoute = FreelancerFindWorkIndexRouteImport.update({
  id: '/freelancer/find-work/',
  path: '/freelancer/find-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdShortlistRoute = JobJobIdShortlistRouteImport.update({
  id: '/job/$jobId/shortlist',
  path: '/job/$jobId/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdEditRoute = JobJobIdEditRouteImport.update({
  id: '/job/$jobId/edit',
  path: '/job/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdApplicantsRoute = JobJobIdApplicantsRouteImport.update({
  id: '/job/$jobId/applicants',
  path: '/job/$jobId/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerFindWorkJobIdIndexRoute =
  FreelancerFindWorkJobIdIndexRouteImport.update({
    id: '/freelancer/find-work/$jobId/',
    path: '/freelancer/find-work/$jobId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StatsSpendingPaymentPaymentIdRoute =
  StatsSpendingPaymentPaymentIdRouteImport.update({
    id: '/spending/payment/$paymentId',
    path: '/spending/payment/$paymentId',
    getParentRoute: () => StatsRoute,
  } as any)
const StatsSpendingContractContractIdRoute =
  StatsSpendingContractContractIdRouteImport.update({
    id: '/spending/contract/$contractId',
    path: '/spending/contract/$contractId',
    getParentRoute: () => StatsRoute,
  } as any)
const FreelancerFindWorkJobIdApplyRoute =
  FreelancerFindWorkJobIdApplyRouteImport.update({
    id: '/freelancer/find-work/$jobId/apply',
    path: '/freelancer/find-work/$jobId/apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobJobIdApplicantsApplicantIdMessageRoute =
  JobJobIdApplicantsApplicantIdMessageRouteImport.update({
    id: '/$applicantId/message',
    path: '/$applicantId/message',
    getParentRoute: () => JobJobIdApplicantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRouteWithChildren
  '/talent': typeof TalentRoute
  '/timer': typeof TimerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/proposals': typeof FreelancerProposalsRoute
  '/freelancer/settings': typeof FreelancerSettingsRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/agency/': typeof AgencyIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/job/$jobId/applicants': typeof JobJobIdApplicantsRouteWithChildren
  '/job/$jobId/edit': typeof JobJobIdEditRoute
  '/job/$jobId/shortlist': typeof JobJobIdShortlistRoute
  '/freelancer/find-work/': typeof FreelancerFindWorkIndexRoute
  '/stats/spending/': typeof StatsSpendingIndexRoute
  '/freelancer/find-work/$jobId/apply': typeof FreelancerFindWorkJobIdApplyRoute
  '/stats/spending/contract/$contractId': typeof StatsSpendingContractContractIdRoute
  '/stats/spending/payment/$paymentId': typeof StatsSpendingPaymentPaymentIdRoute
  '/freelancer/find-work/$jobId/': typeof FreelancerFindWorkJobIdIndexRoute
  '/job/$jobId/applicants/$applicantId/message': typeof JobJobIdApplicantsApplicantIdMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof TalentRoute
  '/timer': typeof TimerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/proposals': typeof FreelancerProposalsRoute
  '/freelancer/settings': typeof FreelancerSettingsRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/agency': typeof AgencyIndexRoute
  '/freelancer': typeof FreelancerIndexRoute
  '/stats': typeof StatsIndexRoute
  '/job/$jobId/applicants': typeof JobJobIdApplicantsRouteWithChildren
  '/job/$jobId/edit': typeof JobJobIdEditRoute
  '/job/$jobId/shortlist': typeof JobJobIdShortlistRoute
  '/freelancer/find-work': typeof FreelancerFindWorkIndexRoute
  '/stats/spending': typeof StatsSpendingIndexRoute
  '/freelancer/find-work/$jobId/apply': typeof FreelancerFindWorkJobIdApplyRoute
  '/stats/spending/contract/$contractId': typeof StatsSpendingContractContractIdRoute
  '/stats/spending/payment/$paymentId': typeof StatsSpendingPaymentPaymentIdRoute
  '/freelancer/find-work/$jobId': typeof FreelancerFindWorkJobIdIndexRoute
  '/job/$jobId/applicants/$applicantId/message': typeof JobJobIdApplicantsApplicantIdMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRouteWithChildren
  '/talent': typeof TalentRoute
  '/timer': typeof TimerRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/proposals': typeof FreelancerProposalsRoute
  '/freelancer/settings': typeof FreelancerSettingsRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/agency/': typeof AgencyIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/job/$jobId/applicants': typeof JobJobIdApplicantsRouteWithChildren
  '/job/$jobId/edit': typeof JobJobIdEditRoute
  '/job/$jobId/shortlist': typeof JobJobIdShortlistRoute
  '/freelancer/find-work/': typeof FreelancerFindWorkIndexRoute
  '/stats/spending/': typeof StatsSpendingIndexRoute
  '/freelancer/find-work/$jobId/apply': typeof FreelancerFindWorkJobIdApplyRoute
  '/stats/spending/contract/$contractId': typeof StatsSpendingContractContractIdRoute
  '/stats/spending/payment/$paymentId': typeof StatsSpendingPaymentPaymentIdRoute
  '/freelancer/find-work/$jobId/': typeof FreelancerFindWorkJobIdIndexRoute
  '/job/$jobId/applicants/$applicantId/message': typeof JobJobIdApplicantsApplicantIdMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/dashboard'
    | '/jobs'
    | '/join'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/timer'
    | '/verify-email'
    | '/agency/profile'
    | '/freelancer/earnings'
    | '/freelancer/profile'
    | '/freelancer/proposals'
    | '/freelancer/settings'
    | '/onboarding/business'
    | '/settings/profile'
    | '/agency/'
    | '/freelancer/'
    | '/stats/'
    | '/job/$jobId/applicants'
    | '/job/$jobId/edit'
    | '/job/$jobId/shortlist'
    | '/freelancer/find-work/'
    | '/stats/spending/'
    | '/freelancer/find-work/$jobId/apply'
    | '/stats/spending/contract/$contractId'
    | '/stats/spending/payment/$paymentId'
    | '/freelancer/find-work/$jobId/'
    | '/job/$jobId/applicants/$applicantId/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contracts'
    | '/dashboard'
    | '/jobs'
    | '/join'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/talent'
    | '/timer'
    | '/verify-email'
    | '/agency/profile'
    | '/freelancer/earnings'
    | '/freelancer/profile'
    | '/freelancer/proposals'
    | '/freelancer/settings'
    | '/onboarding/business'
    | '/settings/profile'
    | '/agency'
    | '/freelancer'
    | '/stats'
    | '/job/$jobId/applicants'
    | '/job/$jobId/edit'
    | '/job/$jobId/shortlist'
    | '/freelancer/find-work'
    | '/stats/spending'
    | '/freelancer/find-work/$jobId/apply'
    | '/stats/spending/contract/$contractId'
    | '/stats/spending/payment/$paymentId'
    | '/freelancer/find-work/$jobId'
    | '/job/$jobId/applicants/$applicantId/message'
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/dashboard'
    | '/jobs'
    | '/join'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/stats'
    | '/talent'
    | '/timer'
    | '/verify-email'
    | '/agency/profile'
    | '/freelancer/earnings'
    | '/freelancer/profile'
    | '/freelancer/proposals'
    | '/freelancer/settings'
    | '/onboarding/business'
    | '/settings/profile'
    | '/agency/'
    | '/freelancer/'
    | '/stats/'
    | '/job/$jobId/applicants'
    | '/job/$jobId/edit'
    | '/job/$jobId/shortlist'
    | '/freelancer/find-work/'
    | '/stats/spending/'
    | '/freelancer/find-work/$jobId/apply'
    | '/stats/spending/contract/$contractId'
    | '/stats/spending/payment/$paymentId'
    | '/freelancer/find-work/$jobId/'
    | '/job/$jobId/applicants/$applicantId/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractsRoute: typeof ContractsRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PostJobRoute: typeof PostJobRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRouteWithChildren
  TalentRoute: typeof TalentRoute
  TimerRoute: typeof TimerRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AgencyProfileRoute: typeof AgencyProfileRoute
  FreelancerEarningsRoute: typeof FreelancerEarningsRoute
  FreelancerProfileRoute: typeof FreelancerProfileRoute
  FreelancerProposalsRoute: typeof FreelancerProposalsRoute
  FreelancerSettingsRoute: typeof FreelancerSettingsRoute
  OnboardingBusinessRoute: typeof OnboardingBusinessRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  AgencyIndexRoute: typeof AgencyIndexRoute
  FreelancerIndexRoute: typeof FreelancerIndexRoute
  JobJobIdApplicantsRoute: typeof JobJobIdApplicantsRouteWithChildren
  JobJobIdEditRoute: typeof JobJobIdEditRoute
  JobJobIdShortlistRoute: typeof JobJobIdShortlistRoute
  FreelancerFindWorkIndexRoute: typeof FreelancerFindWorkIndexRoute
  FreelancerFindWorkJobIdApplyRoute: typeof FreelancerFindWorkJobIdApplyRoute
  FreelancerFindWorkJobIdIndexRoute: typeof FreelancerFindWorkJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/freelancer/': {
      id: '/freelancer/'
      path: '/freelancer'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof FreelancerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/': {
      id: '/agency/'
      path: '/agency'
      fullPath: '/agency/'
      preLoaderRoute: typeof AgencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/business': {
      id: '/onboarding/business'
      path: '/onboarding/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof OnboardingBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/settings': {
      id: '/freelancer/settings'
      path: '/freelancer/settings'
      fullPath: '/freelancer/settings'
      preLoaderRoute: typeof FreelancerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/proposals': {
      id: '/freelancer/proposals'
      path: '/freelancer/proposals'
      fullPath: '/freelancer/proposals'
      preLoaderRoute: typeof FreelancerProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/profile': {
      id: '/freelancer/profile'
      path: '/freelancer/profile'
      fullPath: '/freelancer/profile'
      preLoaderRoute: typeof FreelancerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/earnings': {
      id: '/freelancer/earnings'
      path: '/freelancer/earnings'
      fullPath: '/freelancer/earnings'
      preLoaderRoute: typeof FreelancerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/profile': {
      id: '/agency/profile'
      path: '/agency/profile'
      fullPath: '/agency/profile'
      preLoaderRoute: typeof AgencyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/spending/': {
      id: '/stats/spending/'
      path: '/spending'
      fullPath: '/stats/spending/'
      preLoaderRoute: typeof StatsSpendingIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/freelancer/find-work/': {
      id: '/freelancer/find-work/'
      path: '/freelancer/find-work'
      fullPath: '/freelancer/find-work/'
      preLoaderRoute: typeof FreelancerFindWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/shortlist': {
      id: '/job/$jobId/shortlist'
      path: '/job/$jobId/shortlist'
      fullPath: '/job/$jobId/shortlist'
      preLoaderRoute: typeof JobJobIdShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/edit': {
      id: '/job/$jobId/edit'
      path: '/job/$jobId/edit'
      fullPath: '/job/$jobId/edit'
      preLoaderRoute: typeof JobJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/applicants': {
      id: '/job/$jobId/applicants'
      path: '/job/$jobId/applicants'
      fullPath: '/job/$jobId/applicants'
      preLoaderRoute: typeof JobJobIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/find-work/$jobId/': {
      id: '/freelancer/find-work/$jobId/'
      path: '/freelancer/find-work/$jobId'
      fullPath: '/freelancer/find-work/$jobId/'
      preLoaderRoute: typeof FreelancerFindWorkJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/spending/payment/$paymentId': {
      id: '/stats/spending/payment/$paymentId'
      path: '/spending/payment/$paymentId'
      fullPath: '/stats/spending/payment/$paymentId'
      preLoaderRoute: typeof StatsSpendingPaymentPaymentIdRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/spending/contract/$contractId': {
      id: '/stats/spending/contract/$contractId'
      path: '/spending/contract/$contractId'
      fullPath: '/stats/spending/contract/$contractId'
      preLoaderRoute: typeof StatsSpendingContractContractIdRouteImport
      parentRoute: typeof StatsRoute
    }
    '/freelancer/find-work/$jobId/apply': {
      id: '/freelancer/find-work/$jobId/apply'
      path: '/freelancer/find-work/$jobId/apply'
      fullPath: '/freelancer/find-work/$jobId/apply'
      preLoaderRoute: typeof FreelancerFindWorkJobIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId/applicants/$applicantId/message': {
      id: '/job/$jobId/applicants/$applicantId/message'
      path: '/$applicantId/message'
      fullPath: '/job/$jobId/applicants/$applicantId/message'
      preLoaderRoute: typeof JobJobIdApplicantsApplicantIdMessageRouteImport
      parentRoute: typeof JobJobIdApplicantsRoute
    }
  }
}

interface StatsRouteChildren {
  StatsIndexRoute: typeof StatsIndexRoute
  StatsSpendingIndexRoute: typeof StatsSpendingIndexRoute
  StatsSpendingContractContractIdRoute: typeof StatsSpendingContractContractIdRoute
  StatsSpendingPaymentPaymentIdRoute: typeof StatsSpendingPaymentPaymentIdRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsIndexRoute: StatsIndexRoute,
  StatsSpendingIndexRoute: StatsSpendingIndexRoute,
  StatsSpendingContractContractIdRoute: StatsSpendingContractContractIdRoute,
  StatsSpendingPaymentPaymentIdRoute: StatsSpendingPaymentPaymentIdRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

interface JobJobIdApplicantsRouteChildren {
  JobJobIdApplicantsApplicantIdMessageRoute: typeof JobJobIdApplicantsApplicantIdMessageRoute
}

const JobJobIdApplicantsRouteChildren: JobJobIdApplicantsRouteChildren = {
  JobJobIdApplicantsApplicantIdMessageRoute:
    JobJobIdApplicantsApplicantIdMessageRoute,
}

const JobJobIdApplicantsRouteWithChildren =
  JobJobIdApplicantsRoute._addFileChildren(JobJobIdApplicantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PostJobRoute: PostJobRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRouteWithChildren,
  TalentRoute: TalentRoute,
  TimerRoute: TimerRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AgencyProfileRoute: AgencyProfileRoute,
  FreelancerEarningsRoute: FreelancerEarningsRoute,
  FreelancerProfileRoute: FreelancerProfileRoute,
  FreelancerProposalsRoute: FreelancerProposalsRoute,
  FreelancerSettingsRoute: FreelancerSettingsRoute,
  OnboardingBusinessRoute: OnboardingBusinessRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  AgencyIndexRoute: AgencyIndexRoute,
  FreelancerIndexRoute: FreelancerIndexRoute,
  JobJobIdApplicantsRoute: JobJobIdApplicantsRouteWithChildren,
  JobJobIdEditRoute: JobJobIdEditRoute,
  JobJobIdShortlistRoute: JobJobIdShortlistRoute,
  FreelancerFindWorkIndexRoute: FreelancerFindWorkIndexRoute,
  FreelancerFindWorkJobIdApplyRoute: FreelancerFindWorkJobIdApplyRoute,
  FreelancerFindWorkJobIdIndexRoute: FreelancerFindWorkJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
